### ISSUE TITLE
Regression with PermissionStatus.neverAskAgain

### ISSUE THREAD

**Issue by Zazo032** [Baseflow/flutter-permission-handler#192]
## 🔙 Regression

With version `4.2.0`, when user accepts permissions, it shows as `neverAskAgaing` instead of `granted`.

### Old (and correct) behavior

Output of print: `{PermissionGroup.storage: PermissionStatus.granted}`

### Current behavior

Output of print: `{PermissionGroup.storage: PermissionStatus.neverAskAgain}`
The next time user clicks the button that runs the code, it shows as `granted`.

### Reproduction steps

```dart
if (await PermissionHandler().checkPermissionStatus(PermissionGroup.storage) != PermissionStatus.granted) {
  Map<PermissionGroup, PermissionStatus> permissions = await PermissionHandler().requestPermissions([PermissionGroup.storage]);
  print(permissions);
  if (permissions[PermissionGroup.storage] != PermissionStatus.granted) {
    // Not granted
  }
}
```

### Configuration

**Version:** 4.2.0

**Platform:** 
- [ ] :iphone: iOS (not tested)
- [x] :robot: Android

**Comment by aleor** [comment]
Getting this too. Requesting permissions for camera on Android, select "Allow" and result is "neverAskAgain" (5).
4.1.0 doesn't seem to have this problem.

**Comment by mvanbeusekom** [comment]
@Zazo032, @aleor, thank you for this report. The "neverAskAgain" status is introduced in version 4.2.0 and clearly has a bug in its implementation.

I will look into it and provide a hotfix a.s.a.p. in the meantime I suggest you stick with version 4.1.0.

**Comment by mvanbeusekom** [comment]
@Zazo032, @aleor, I have just released a hotfix (version 4.2.0+hotfix.1) which should fix this error. 

Would be extremely helpful if you could confirm?

**Comment by aleor** [comment]
@mvanbeusekom Thank you, just tried with hotfix.1 and still got 'neverAskAgain' result. Switched back to 4.1 and got 'granted', as expected.

**Comment by aleor** [comment]
@mvanbeusekom To be more specific, my flow is:
- `await PermissionHandler().checkPermissionStatus(PermissionGroup.camera);` => returns `PermissionStatus.denied` on a first check (right after app is installed and launched);
- then I'm calling `await PermissionHandler().requestPermissions([PermissionGroup.camera]);`, which returns `PermissionStatus.neverAskAgain`, no matter which option is selected; BUT - at the same time, I see that camera becomes `allowed` under app's permission settings;
- if I try to call `await PermissionHandler().checkPermissionStatus(PermissionGroup.camera);` again after that, I'm getting `PermissionStatus.allowed`, as expected.

So the problem here is a returned value from `requestPermissions()` call, which says `neverAskAgain` always.

**Comment by dy1023348109** [comment]
Getting this issue too, use 4.2.0+hotfix.1 still have this issue, but 4.1.0 work fine.

**Comment by mvanbeusekom** [comment]
@aleor thank you for the extensive test report, I will start looking into it now

**Comment by mvanbeusekom** [comment]
@Zazo032, @aleor, @dy1023348109, just release a new version of the plugin which should have fixed the bug. Turns out I made a stupid mistake and not completely merged the bug fix.

I have tested `4.2.0+hotfix.2` using the example app it looks like it is working correctly now. Would very much appreciate your experiences.

**Comment by dy1023348109** [comment]
thank you for you work,
