### ISSUE TITLE
Permission.locationAlways.status gives wrong answer in iOS

### ISSUE THREAD

**Issue by sc00n** [Baseflow/flutter-permission-handler#721]
When I first ask permission on iOS for locationWhenInUse and answer with '_Allow While Using App_', Permission.locationAlways.status will return granted (even though location access is set to 'While Using the App' and not to 'Always').

When I manually (in settings) set the permission to '_Never_' or '_Ask Next Time_' and then back to 'While Using the App',  Permission.locationAlways.status will return denied (the correct answer).

When I first ask permission on iOS for location and answer with '_Allow Once_' or '_Don't Allow_', Permission.locationAlways.status will return denied (this is correct).

I use permission_handler: ^8.1.6

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.6 20G165 darwin-x64, locale en-BE)
    • Flutter version 2.2.1 at /Users/app/flutter
    • Framework revision 02c026b03c (5 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/merijnmestdagh/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • Merijn’s iPhone (mobile) • 00008020-0009601E1199002E • ios            • iOS 14.8
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 95.0.4638.69
```

</details>

**Comment by Harsh1052** [comment]
Same error occur Show location always permission granted without make grated and show permanentlyDenied without make permanentlyDenied

**Comment by cormalenv** [comment]
Concur.  permission_handler 8.3.0, on iOS15 emulator

`Permission.locationAlways.status` returning `PermissionStatus.granted` where location access is set to `While Using the App`

**Comment by sc00n** [comment]
@cormalenv I first ask Permission.locationWhenInUse

In the next screen, I check if Permission.always is given. If it is not given I give them some information and subsequently redirect them to settings. In the mean while I keep checking if permission.always is already given. If so, the screen (in app) says that everything is fine now.

**Comment by RohithKilaparthi** [comment]
````
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)
````

I get this unhandled exception and no prompt shows up. Any idea on how to resolve this?

**Comment by cormalenv** [comment]
@sc00n as a follow up and after further testing it appears there a significant issues around location permission handling particularly on IOS, suggesting my earlier advice may not be of much use. I note there are multiple open reports of similar issues that also may be related.(@mvanbeusekom tagging given your comments on a many of these). 

I've run a number of tests on different versions of the plugin with a range of failures. On  8.3.0 specifically then...

iOS simulator (some on iPhone)
- requesting/granting 'when in use' changes status to granted but location.status to 'permanently denied'
- requesting 'when in use' more than once shuts down app without error return
- requesting 'always' hangs with no returned response
- requesting 'always' again returns with ERROR_ALREADY_REQUESTING_PERMISSIONS

Android emulator
- requesting 'when in use' is OK
- requesting 'Always' sets permission to granted, but shows no system request dialog and app system location settings indicate  'when in use' only remains.

Seems like there is a bit to do here then. 

<details>
  <summary>Flutter Doctor Output</summary>
  
 [✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-arm, locale en-AU)
    • Flutter version 2.5.3 at /Users/.../Library/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 mini (mobile)     • D12A97B4-6173-4705-82DD-126F7A9EE754 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

</details>

**Comment by Yuganka** [comment]
+1. I am also facing the same issue.

**Comment by cormalenv** [comment]
It might be worth checking that your usage description for `Always` in `info.plist` uses the key `NSLocationAlwaysAndWhenInUseUsageDescription` rather than `NSLocationAlwaysUsageDescription`. `NSLocationAlwaysUsageDescription` is deprecated from iOS11 and will result in problems if left in (`NSLocationWhenInUseUsageDescription` should remain however). 

Also as previously stated requesting 'Always' is not possible (11+ at least) and results in the following error from permission handler `To use location in iOS8 you need to define NSLocationAlwaysUsageDescription in the app bundle's Info.plist file`. This message likely needs to be adjusted to better reference the situation, and location always request removed or modified to cater for iOS11+. 

Note: On iOS simulator, I couldn't `Catch` the error. AS simply disconnects, XCode reports but doesn't catch.

**Comment by kamami** [comment]
Any news on this? Will this be fixed?

**Comment by mvanbeusekom** [comment]
Thanks to @lukaskurz for creating PR #800, this issue should have been resolved. Please run `flutter pub upgrade` to update to the latest version.

**Comment by mvanbeusekom** [comment]
@jbxbergdev can you make sure your app is using the latest version of the `permission_handler_Apple` package. 

You can verify this by checking the version listed in the `pubspec.lock` file. The correct version should be `9.0.4`. If this is not the case please make sure to run `flutter pub upgrade`.

**Comment by jbxbergdev** [comment]
The code is
```
  final foregroundStatus = await Permission.locationWhenInUse.request();

  if (foregroundStatus.isGranted) {
    final backgroundStatus = (await Permission.locationAlways.request()); // returns wrongfully as granted with no dialog showing up
  }
```

**Comment by JulianBissekkou** [comment]
Can we reopen this issue since we are still facing this issue in 10.4.5.

**Comment by prokons** [comment]
I'm also facing the same issue, locationAlways return granted but actually only locationwhereinuse is granted on my iphone

```
      if (await Permission.locationWhenInUse.request() == PermissionStatus.granted) {
        if (await Permission.locationAlways.request() == PermissionStatus.granted) locationStatus = true;
}```

**Comment by Manigandasaravanan** [comment]
I solved this issue by this way,

First I request for locationWhenInUse. Then I request for locationAlways. Please find my below code.

if (await Permission.locationWhenInUse.isGranted) {
} else {
      await Permission.locationWhenInUse.request();
}

then,
if (await Permission.locationWhenInUse.isGranted) {
      await Permission.locationAlways.request();
} else {
      openAppSettings();
}

Please note: Don't use Permission.location.request(); instead use Permission.locationWhenInUse.request();
